global_planner:
  costmap:
    height: 10
    width: 10
    resolution: .05
    origin_x: -5
    origin_y: -5
    plugins: 
     - {name: static, type: 'costmap_2d::StaticLayer'}
     - {name: social, type: 'social_navigation_layers::ProxemicLayer'}
    publish_frequency: 1.0

